### ISSUE TITLE
Prevent rounding for latitude and longitude for encodeNmeaPacket?

### ISSUE THREAD

**Issue by matmis** [101100/nmea-simple#13]
For my application is the encoded latitude and longitude is not precise enough.

**Comment by matmis** [comment]
I changed `m.toFixed(2)` to `m.toFixed(20)` [here](https://github.com/101100/nmea-simple/blob/7db0108fc1eff71af18fc4e07f2dc7ce37faa04b/helpers.ts#L115)

**Comment by 101100** [comment]
My initial understanding was that it should always be 2 decimal places, but I have found other cases with more searching.  I'm not sure 20 decimal places is practical, though.  What if we defaulted to some middle value but let you specify a precision if you want?

That portion is for the minutes, which are 1 nautical mile at the equator.  That means that a precision of 2 decimal places (or 0.01) is 18.52 meters.  10 decimal places give a resolution of 185.2 nanometers, which still seems like a bit much.  How much precision do you need?

How about a default of 6 decimal places?  That gives a precision of 1.852 millimeters.

**Comment by matmis** [comment]
Yes that would be great!

**Comment by 101100** [comment]
Version v3.1.0 now uses 6 decimal places.
