### ISSUE TITLE
DTM message is not supported

### ISSUE THREAD

**Issue by goestrip** [101100/nmea-simple#8]
Datum reference message is not (yet) supported.
see specs here: 
[http://www.catb.org/gpsd/NMEA.html#_dtm_datum_reference]
or
[https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GPDTM.html]

**Comment by 101100** [comment]
@goestrip Could you post a few example strings from your GPS?  It is helpful to have an example to test with and the example may as well be real.

**Comment by goestrip** [comment]
There actually a couple of message not handled, but nmea-Simple throw gracefully.
- DTM :
`$GNDTM,W84,,0.0,N,0.0,E,0.0,W84*71`
- GNS:
`$GNGNS,160642.50,4137.9134296,N,00227.6883064,E,FFNN,11,1.10,11.977,48.516,0.5,0000,V*14`
- ZDA : 
`$GNZDA,160642.50,09,11,2017,00,00*77`
- GBS: 
`$GNGBS,160642.50,0.1,0.1,0.3,,,,,,*5E`

I also thank you for this Lib which is really easy and usefull !

**Comment by 101100** [comment]
Do you want to use those other packets, or just avoid the exceptions?  I could make version 3.0 return a special value if an unknown packet is found.

**Comment by PBV404** [comment]
Well, not really, not at the moment at least. My remark was more to keep that nice lib up to date. The exception mechanism is perfectly fine. I don't think there is much penalty with a try / catch. Though it might be worth timing it. But i'm currently parsing NMEA at 10Hz on a mobile phone with this lib, and it works well.

**Comment by goestrip** [comment]
Well, not really, not at the moment at least. My remark was more to keep that nice lib up to date. The exception mechanism is perfectly fine. I don't think there is much penalty with a try / catch. Though it might be worth timing it. But i'm currently parsing NMEA at 10Hz on a mobile phone with this lib, and it works well.

**Comment by 101100** [comment]
@goestrip OK, I have an idea for version 3.0 to add a `parsed` flag to each packet.  Then I can return:

```js
{
    parsed: false,
    error: "Packet had invalid checksum"
}
```

or

```js
{
    parsed: false,
    sentenceId: "DTM",
    talkerId: "GP",
    error: "Packet type is unknown"
}
```

I've also implemented `DTM` and I'll implement the other three two, since that is not too much work. 

Also thanks for the feedback.  It is nice to know the library is useful for someone.

**Comment by goestrip** [comment]
You're welcome 👍 . 
And yes your idea looks good, will be easier to detect which packet caused the problem, if any.
