### ISSUE TITLE
NMEA parsing of latitude and longitude should be rounded

### ISSUE THREAD

**Issue by FredrikBlix** [101100/nmea-simple#9]
I was parsing the GPRMC message and saw that the float value representing the positions had alot more decimals than the precision in the NMEA string.

```
$GPRMC,153103.0,A,6309.605159,N,01445.161351,E,0.0,,151118,0.0,E,A*24'
```

```
{ 
  sentenceId: 'RMC',
  sentenceName: 'Recommended minimum navigation information',
  datetime: 2018-11-15T15:31:03.000Z,
  status: 'valid',
  latitude: 63.16008598333333,
  longitude: 14.752689183333333,
  speedKnots: 0,
  trackTrue: 0,
  variation: 0,
  variationPole: 'E',
  faaMode: 'A',
  talkerId: 'GP'
}
```

Shouldn't the value be rounded into  7 decimals presicion, into something like this?

```
{ 
  sentenceId: 'RMC',
  sentenceName: 'Recommended minimum navigation information',
  datetime: 2018-11-15T15:31:03.000Z,
  status: 'valid',
  latitude: 63.1600860,
  longitude: 14.7526892,
  speedKnots: 0,
  trackTrue: 0,
  variation: 0,
  variationPole: 'E',
  faaMode: 'A',
  talkerId: 'GP'
}
```

Before returning from the `helpers.ts` `parseLongitude` and `parseLatitude` functions, maybe make a round value like this:

```
    latitude = Math.round(latitude * 10000000) / 10000000;
    longitude = Math.round(longitude * 10000000) / 10000000;
```

**Comment by 101100** [comment]
@FredrikBlix What is the helpfulness of rounding the values?  I could add that, but I don't see the purpose.

**Comment by FredrikBlix** [comment]
Well, it's not a biggie. But the number of decimals gives information of the precision of a value. 1.0 is more precise than 1.

The NMEA string contains 6 decimals precision. you divide that with 60 to transform this into WGS84. that operation should add maximum 2 decimals to the precision. If you divide by 10 you get one more decimal and if you divide by 100 you get two, dividing by 60 should be something in between. So, 7 (as I wrote before) or perhaps rather 8 decimals to maintain the precision.

**Comment by guerrillacontra** [comment]
I agree, as this is a protocol based formatting we should try and stick to what it requires (7 decimal places of accuracy).

Something like:

```
export function roundTo( val:number, place :number):number {
  const place = place || 0; 
  const  fact = Math.pow( 10, place ); 
  return Math.round( val * fact ) / fact; 
}

const lat = roundTo(lat, 7);
const lon = roundTo(lon, 7);

```



With 7 decimal places should do the job however I prefer @FredrikBlix rounding as we know ahead what precision is needed and his is greater performance while being less code.

**Comment by 101100** [comment]
@FredrikBlix Sorry for the slow reply.  I was only reminded of this with the new comment.

While there are not as many significant digits as given by the resulting values, I don't want to add the rounding to the library.  I think that the rounding should be done by display code and not by this library.  Here are the reasons:

1. Floating-point numbers are not the right tool for expressing significant digits and therefore should not be sued to represent that information.  For example, if you execute `console.log(0.1 * 0.2)`, you will get `0.020000000000000004` logged to the console.  This means that even if you put "properly rounded" values in, you aren't guaranteed to get reasonable values out.  In addition, the library might return `2.25`, which does not indicate the number of significant digits either.

2. Rounding loses information.  Consider the input example you used of 63 degrees and 9.605159 minutes.  The minutes converted to degrees is `9.605159 / 60 = 0.16008598333`.  60 is a "perfect" value, we have 7 significant digits in the minutes, so with rounding you'd get `63.1600860`.  If you convert that value back to degrees and minutes, you'd get `9.605160` minutes (still 7 significant digits).  You could round to more decimal places, but then you are back to returning "too many" digits.

3. Not all GPS receivers give the same number of decimal places.  I have seen examples with only two, for example [here](http://aprs.gids.nl/nmea/#rmc).

4. The rounding takes computational time.  This means that the library is slower for all users even if it is not desired by some people.
